angular.module('cal').config(function($stateProvider,$urlRouterProvider){
    $stateProvider
        .state("executeResults",{
            url:"/executeResults",
            templateUrl:'views/results.html',
            controller:'resultController'
        })
        .state("productList",{
            url:"/productList",
            templateUrl:'views/productList.html',
            controller:'productListController'
        })
        .state("sumCount",{
            url:"/sumCount",
            templateUrl:'views/sumCount.html',
            controller:'sumCountController'
        })
})